import("//build/config/features.gni")
import("//build/config/compontents_extensions_build.gni")
import("//build/config/ui.gni")
import("//testing/test.gni")
import("//tools/grit/repack.gni")

assert(enable_extensions_in_components)


static_library("test_support") {
  testonly = true

  sources = [
    "../browser/chrome_extension_test_notification_observer.cc",
    "../browser/chrome_extension_test_notification_observer.h",
    "../browser/chrome_test_extension_loader.cc",
    "../browser/chrome_test_extension_loader.h",
    "../browser/extension_management_test_util.cc",
    "../browser/extension_management_test_util.h",
    "../browser/extension_service_test_base.cc",
    "../browser/extension_service_test_base.h",
    "../browser/extension_service_test_with_install.cc",
    "../browser/extension_service_test_with_install.h",
    "../browser/extension_service_user_test_base.cc",
    "../browser/extension_service_user_test_base.h",
    "../browser/fake_crx_installer.cc",
    "../browser/fake_crx_installer.h",
    "../browser/load_error_waiter.cc",
    "../browser/load_error_waiter.h",
    "../browser/mock_crx_installer.cc",
    "../browser/mock_crx_installer.h",
    "../browser/test_extension_service.cc",
    "../browser/test_extension_service.h",
    "../browser/test_extension_system.cc",
    "../browser/test_extension_system.h",
    "../common/manifest_tests/chrome_manifest_test.cc",
    "../common/manifest_tests/chrome_manifest_test.h",
  ]

  deps = [
    "//base",
    "//components/crx_file",
    "//components/extensions/browser",
    "//components/extensions/common",
    "//components/extensions/renderer",
    "//components/policy/core/common:test_support",
    "//components/safe_browsing/core/browser/db:database_manager",
    "//components/safe_browsing/core/browser/db:v4_test_util",
    "//components/services/unzip:in_process",
    "//components/services/unzip/content",
    "//components/sessions",
    "//components/value_store:test_support",
    "//content/public/browser",
    "//content/test:test_support",
    "//extensions:test_support",
    "//extensions/browser",
    "//extensions/browser:test_support",
    "//extensions/shell:app_shell_lib",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "../browser/api/chrome_extensions_api_client_unittest.cc",
    "../browser/api/device_permissions_manager_unittest.cc",
    "../browser/api/runtime/chrome_runtime_api_delegate_unittest.cc",
    "../browser/chrome_content_verifier_unittest.cc",
    "../browser/component_loader_unittest.cc",
    "../common/manifest_tests/extension_manifests_chromepermission_unittest.cc",
    "../common/manifest_tests/extension_manifests_contentsecuritypolicy_unittest.cc",
    "../common/manifest_tests/extension_manifests_default_extent_path_unittest.cc",
    "../common/manifest_tests/extension_manifests_devtools_unittest.cc",
    "../common/manifest_tests/extension_manifests_experimental_unittest.cc",
    "../common/manifest_tests/extension_manifests_icons_unittest.cc",
    "../common/manifest_tests/extension_manifests_initvalue_unittest.cc",
    "../common/manifest_tests/extension_manifests_launch_unittest.cc",
    "../common/manifest_tests/extension_manifests_manifest_version_unittest.cc",
    "../common/manifest_tests/extension_manifests_name_unittest.cc",
    "../common/manifest_tests/extension_manifests_offline_unittest.cc",
    "../common/manifest_tests/extension_manifests_old_unittest.cc",
    "../common/manifest_tests/extension_manifests_options_unittest.cc",
    "../common/manifest_tests/extension_manifests_override_unittest.cc",
    "../common/manifest_tests/extension_manifests_platformapp_unittest.cc",
    "../common/manifest_tests/extension_manifests_portsinpermissions_unittest.cc",
    "../common/manifest_tests/extension_manifests_sample_unittest.cc",
    "../common/manifest_tests/extension_manifests_ui_unittest.cc",
    "../common/manifest_tests/extension_manifests_validapp_unittest.cc",
    "../common/manifest_tests/extension_manifests_web_accessible_resources_unittest.cc",
    "../common/manifest_tests/extension_manifests_web_unittest.cc",
    "../common/manifest_tests/extension_manifests_webview_accessible_resources_unittest.cc",
    "../common/manifest_tests/permissions_parser_unittest.cc",
    "../common/manifest_unittest.cc",
  ]

  data = [
    "//base/test/data/",
    "//components/test/data/",
    "//extensions/test/data/",
  ]

  deps = [
    ":test_support",
    "//services/device/public/cpp:test_support",
  ]

  public_deps = [ "//base/test:test_support" ]
}

repack("extensions_tests_pak") {
  testonly = true
  sources = [
    "$root_gen_dir/components/components_resources.pak",
    "$root_gen_dir/components/strings/components_strings_en-US.pak",
    "$root_gen_dir/content/content_resources.pak",
    "$root_gen_dir/extensions/extensions_browser_resources_100_percent.pak",
    "$root_gen_dir/extensions/extensions_renderer_resources.pak",
    "$root_gen_dir/extensions/extensions_resources.pak",
    "$root_gen_dir/extensions/strings/extensions_strings_en-US.pak",
    "$root_gen_dir/net/net_resources.pak",
    "$root_gen_dir/third_party/blink/public/resources/blink_resources.pak",
    "$root_gen_dir/third_party/blink/public/resources/blink_scaled_resources_100_percent.pak",
    "$root_gen_dir/third_party/blink/public/strings/blink_strings_en-US.pak",
  ]

  output = "$root_out_dir/extensions_tests_resources.pak"
  deps = [
    "//components/resources",
    "//components/strings",
    "//content:content_resources",
    "//content/browser/resources:resources",
    "//extensions:extensions_browser_resources_grit",
    "//extensions:extensions_renderer_resources_grit",
    "//extensions:extensions_resources_grd_grit",
    "//extensions/strings",
    "//extensions/strings:strings_grit",
    "//mojo/public/js:resources",
    "//net:net_resources",
    "//third_party/blink/public:resources",
    "//third_party/blink/public:scaled_resources_100_percent",
    "//third_party/blink/public/strings",
  ]
}

test("extensions_in_components_unittests") {
  use_xvfb = use_xvfb_in_this_config
  testonly = true

  sources = [
    "run_all_unittests.cc",
    "test_extension_environment.cc",
    "test_extension_environment.h",
    "test_extension_paths.cc",
    "test_extension_paths.h",
  ]

  data = [
    "$root_out_dir/extensions_tests_resources.pak",
    "$root_out_dir/ui_test.pak",
    "//chrome/test/data/extensions/",
  ]

  deps = [
    ":unit_tests",
    ":test_support",
    "//content/public/browser",
    "//content/public/common",
    "//components/embedder_support:browser_util",
    "//extensions/common",
    "//extensions:shell_and_test_pak",
    "//gin:v8_snapshot_assets",
    "//testing/gtest",
    "//ui/base",
    "//ui/resources:ui_test_pak",
  ]

  if (is_android) {
    deps += [
      "//base:base_unittest_support_java",
      "//content/public/android:content_java",
      "//ui/android:ui_java",
    ]
  }

  public_deps = [
    "//components/extensions/browser/api",
    "//components/extensions/browser/api:api_registration",
    "//components/strings:components_strings",
  ]
}