import("//build/buildflag_header.gni")
import("//build/config/features.gni")
import("//build/config/compontents_extensions_build.gni")

assert(enable_extensions_in_components)

component("common") {
  sources = [
    "chrome_extensions_client.cc",
    "chrome_extensions_client.h",
    "chrome_resource_request_blocked_reason.h",
    "extension_constants.cc",
    "extension_constants.h",
    "initialize_extensions_client.cc",
    "initialize_extensions_client.h",
    "permissions/chrome_permission_message_provider.cc",
    "permissions/chrome_permission_message_provider.h",
  ]
  deps = [
    "//base",
    "//extensions/common:core_api_provider",
    "//extensions:extensions_resources",
  ]

  public_deps = [
    "//components/extensions/common/api",
    "//components/extensions/common/api:extensions_features",
  ]

  defines = [ "IS_EXETENSIONS_IMPL" ]
}

buildflag_header("buildflags") {
  header = "buildflags.h"
  flags = [ "ENABLE_EXTENSIONS_IN_COMPONENTS=$enable_extensions_in_components" ]
}
