import("//build/config/features.gni")
import("//build/config/compontents_extensions_build.gni")
import("//build/config/ui.gni")
import("//testing/test.gni")

assert(enable_extensions_in_components)

component("browser") {
  sources = [
    "active_install_data.cc",
    "active_install_data.h",
    "api/activity_log_private/activity_log_private_api.cc",
    "api/activity_log_private/activity_log_private_api.h",
    "api/api_browser_context_keyed_service_factories.cc",
    "api/api_browser_context_keyed_service_factories.h",
    "api/autofill_private/autofill_private_api.cc",
    "api/autofill_private/autofill_private_api.h",
    "api/bookmark_manager_private/bookmark_manager_private_api.cc",
    "api/bookmark_manager_private/bookmark_manager_private_api.h",
    "api/bookmarks/bookmark_api_constants.cc",
    "api/bookmarks/bookmark_api_constants.h",
    "api/bookmarks/bookmarks_api.cc",
    "api/bookmarks/bookmarks_api.h",
    "api/braille_display_private/braille_display_private_api.cc",
    "api/braille_display_private/braille_display_private_api.h",
    "api/browsing_data/browsing_data_api.cc",
    "api/browsing_data/browsing_data_api.h",
    "api/chrome_extensions_api_client.cc",
    "api/chrome_extensions_api_client.h",
    "api/content_settings/content_settings_api.cc",
    "api/content_settings/content_settings_api.h",
    "api/context_menus/context_menus_api.cc",
    "api/context_menus/context_menus_api.h",
    "api/cookies/cookies_api.cc",
    "api/cookies/cookies_api.h",
    "api/dashboard_private/dashboard_private_api.cc",
    "api/dashboard_private/dashboard_private_api.h",
    "api/debugger/debugger_api.cc",
    "api/debugger/debugger_api.h",
    "api/desktop_capture/desktop_capture_api.cc",
    "api/desktop_capture/desktop_capture_api.h",
    "api/developer_private/developer_private_api.cc",
    "api/developer_private/developer_private_api.h",
    "api/downloads/downloads_api.cc",
    "api/downloads/downloads_api.h",
    "api/downloads_internal/downloads_internal_api.cc",
    "api/downloads_internal/downloads_internal_api.h",
    "api/enterprise_hardware_platform/enterprise_hardware_platform_api.cc",
    "api/enterprise_hardware_platform/enterprise_hardware_platform_api.h",
    "api/enterprise_reporting_private/enterprise_reporting_private_api.cc",
    "api/enterprise_reporting_private/enterprise_reporting_private_api.h",
    "api/extension_action/extension_action_api.cc",
    "api/extension_action/extension_action_api.h",
    "api/extension_action/extension_page_actions_api_constants.cc",
    "api/extension_action/extension_page_actions_api_constants.h",
    "api/font_settings/font_settings_api.cc",
    "api/font_settings/font_settings_api.h",
    "api/gcm/gcm_api.cc",
    "api/gcm/gcm_api.h",
    "api/history/history_api.cc",
    "api/history/history_api.h",
    "api/identity/identity_api.cc",
    "api/identity/identity_api.h",
    "api/identity/identity_clear_all_cached_auth_tokens_function.cc",
    "api/identity/identity_clear_all_cached_auth_tokens_function.h",
    "api/identity/identity_constants.cc",
    "api/identity/identity_constants.h",
    "api/identity/identity_get_accounts_function.cc",
    "api/identity/identity_get_accounts_function.h",
    "api/identity/identity_get_auth_token_function.cc",
    "api/identity/identity_get_auth_token_function.h",
    "api/identity/identity_get_profile_user_info_function.cc",
    "api/identity/identity_get_profile_user_info_function.h",
    "api/identity/identity_launch_web_auth_flow_function.cc",
    "api/identity/identity_launch_web_auth_flow_function.h",
    "api/identity/identity_remove_cached_auth_token_function.cc",
    "api/identity/identity_remove_cached_auth_token_function.h",
    "api/idltest/idltest_api.cc",
    "api/idltest/idltest_api.h",
    "api/image_writer_private/image_writer_private_api.cc",
    "api/image_writer_private/image_writer_private_api.h",
    "api/instance_id/instance_id_api.cc",
    "api/instance_id/instance_id_api.h",
    "api/language_settings_private/language_settings_private_api.cc",
    "api/language_settings_private/language_settings_private_api.h",
    "api/notifications/notifications_api.cc",
    "api/notifications/notifications_api.h",
    "api/omnibox/omnibox_api.cc",
    "api/omnibox/omnibox_api.h",
    "api/passwords_private/passwords_private_api.cc",
    "api/passwords_private/passwords_private_api.h",
    "api/permissions/permissions_api.cc",
    "api/permissions/permissions_api.h",
    "api/preference/preference_api.cc",
    "api/preference/preference_api.h",
    "api/permissions/permissions_api_helpers.cc",
    "api/permissions/permissions_api_helpers.h",
    "api/reading_list/reading_list_api.cc",
    "api/reading_list/reading_list_api.h",
    "api/reading_list/reading_list_api_constants.cc",
    "api/reading_list/reading_list_api_constants.h",
    "api/resources_private/resources_private_api.cc",
    "api/resources_private/resources_private_api.h",
    "api/runtime/chrome_runtime_api_delegate.cc",
    "api/runtime/chrome_runtime_api_delegate.h",
    "api/safe_browsing_private/safe_browsing_private_api.cc",
    "api/safe_browsing_private/safe_browsing_private_api.h",
    "api/search/search_api.cc",
    "api/search/search_api.h",
    "api/sessions/session_id.cc",
    "api/sessions/session_id.h",
    "api/sessions/sessions_api.cc",
    "api/sessions/sessions_api.h",
    "api/settings_private/settings_private_api.cc",
    "api/settings_private/settings_private_api.h",
    "api/side_panel/side_panel_api.cc",
    "api/side_panel/side_panel_api.h",
    "api/system_private/system_private_api.cc",
    "api/system_private/system_private_api.h",
    "api/tab_capture/tab_capture_api.cc",
    "api/tab_capture/tab_capture_api.h",
    "api/tab_groups/tab_groups_api.cc",
    "api/tab_groups/tab_groups_api.h",
    "api/tabs/tabs_api.cc",
    "api/tabs/tabs_api.h",
    "api/tabs/tabs_constants.cc",
    "api/tabs/tabs_constants.h",
    "api/tabs/tabs_windows_api.cc",
    "api/tabs/tabs_windows_api.h",
    "api/top_sites/top_sites_api.cc",
    "api/top_sites/top_sites_api.h",
    "api/web_authentication_proxy/web_authentication_proxy_api.cc",
    "api/web_authentication_proxy/web_authentication_proxy_api.h",
    "api/web_navigation/web_navigation_api.cc",
    "api/web_navigation/web_navigation_api.h",
    "api/web_navigation/web_navigation_api_constants.cc",
    "api/web_navigation/web_navigation_api_constants.h",
    "api/webrtc_audio_private/webrtc_audio_private_api.cc",
    "api/webrtc_audio_private/webrtc_audio_private_api.h",
    "api/webrtc_desktop_capture_private/webrtc_desktop_capture_private_api.cc",
    "api/webrtc_desktop_capture_private/webrtc_desktop_capture_private_api.h",
    "api/webrtc_logging_private/webrtc_logging_private_api.cc",
    "api/webrtc_logging_private/webrtc_logging_private_api.h",
    "api/webstore_private/webstore_private_api.cc",
    "api/webstore_private/webstore_private_api.h",
    "browser_context_keyed_service_factories.cc",
    "browser_context_keyed_service_factories.h",
    "chrome_browser_context_keyed_service_factories.cc",
    "chrome_browser_context_keyed_service_factories.h",
    "chrome_component_extension_resource_manager.cc",
    "chrome_component_extension_resource_manager.h",
    "chrome_content_browser_client_extensions_part.cc",
    "chrome_content_browser_client_extensions_part.h",
    "chrome_content_browser_client_extensions_part_bindings.cc",
    "chrome_content_verifier_delegate.cc",
    "chrome_content_verifier_delegate.h",
    "chrome_extension_browser_constants.cc",
    "chrome_extension_browser_constants.h",
    "chrome_extension_frame_host.cc",
    "chrome_extension_frame_host.h",
    "chrome_extension_host_delegate.cc",
    "chrome_extension_host_delegate.h",
    "chrome_extension_web_contents_observer.cc",
    "chrome_extension_web_contents_observer.h",
    "chrome_extensions_browser_api_provider.cc",
    "chrome_extensions_browser_api_provider.h",
    "chrome_extensions_browser_client.cc",
    "chrome_extensions_browser_client.h",
    "chrome_process_manager_delegate.cc",
    "chrome_process_manager_delegate.h",
    "chrome_url_request_util.cc",
    "chrome_url_request_util.h",
    "chrome_zipfile_installer.cc",
    "chrome_zipfile_installer.h",
    "component_loader.cc",
    "component_loader.h",
    "convert_user_script.cc",
    "convert_user_script.h",
    "corrupted_extension_reinstaller.cc",
    "corrupted_extension_reinstaller.h",
    "crx_installer.cc",
    "crx_installer.h",
    "error_console/error_console.cc",
    "error_console/error_console.h",
    "error_console/error_console_factory.cc",
    "error_console/error_console_factory.h",
    "event_router_forwarder.cc",
    "event_router_forwarder.h",
    "extension_action_runner.cc",
    "extension_action_runner.h",
    "extension_action_storage_manager.cc",
    "extension_action_storage_manager.h",
    "extension_assets_manager.cc",
    "extension_assets_manager.h",
    "extension_error_controller.cc",
    "extension_error_controller.h",
    "extension_error_ui.h",
    "extension_error_ui_default.cc",
    "extension_error_ui_default.h",
    "extension_install_prompt.cc",
    "extension_install_prompt.h",
    "extension_install_prompt_show_params.cc",
    "extension_install_prompt_show_params.h",
    "extension_management.cc",
    "extension_management.h",
    "extension_management_constants.cc",
    "extension_management_constants.h",
    "extension_management_internal.cc",
    "extension_management_internal.h",
    "extension_service.cc",
    "extension_service.h",    
    "extension_system_factory.cc",
    "extension_system_factory.h",
    "extension_system_impl.cc",
    "extension_system_impl.h",
    "extension_util.cc",
    "extension_util.h",
    "extension_webkit_preferences.cc",
    "extension_webkit_preferences.h",
    "install_gate.h",
    "install_observer.cc",
    "install_observer.h",
    "install_prompt_permissions.cc",
    "install_prompt_permissions.h",
    "install_signer.cc",
    "install_signer.h",
    "install_tracker.cc",
    "install_tracker.h",
    "install_tracker_factory.cc",
    "install_tracker_factory.h",
    "install_verifier.cc",
    "install_verifier.h",
    "install_verifier_factory.cc",
    "install_verifier_factory.h",
    "installed_loader.cc",
    "installed_loader.h",
    "load_error_reporter.cc",
    "load_error_reporter.h",
    "permissions_updater.cc",
    "permissions_updater.h",
    "shared_module_service.cc",
    "shared_module_service.h",
    "site_permissions_helper.cc",
    "site_permissions_helper.h",
    "standard_management_policy_provider.cc",
    "standard_management_policy_provider.h",
    "unpacked_installer.cc",
    "unpacked_installer.h",
    "user_script_listener.cc",
    "user_script_listener.h",
  ]
  deps = [
    "//components/javascript_dialogs",
    "//components/reading_list/core",
    "//components/resources",
    "//components/resources:component_extension_resources",
    "//components/signin/core/browser",
    "//components/spellcheck/browser",
    "//components/sync_sessions",
    "//extensions/browser",
    "//extensions/common",
    "//extensions:extensions_resources",
  ]
  public_deps = [
  ]

  defines = [ "IS_EXETENSIONS_IMPL" ]
}


static_library("test_support") {
  testonly = true

  sources = [
    "chrome_extension_test_notification_observer.cc",
    "chrome_extension_test_notification_observer.h",
    "chrome_test_extension_loader.cc",
    "chrome_test_extension_loader.h",
    "extension_management_test_util.cc",
    "extension_management_test_util.h",
    "extension_service_test_base.cc",
    "extension_service_test_base.h",
    "extension_service_test_with_install.cc",
    "extension_service_test_with_install.h",
    "extension_service_user_test_base.cc",
    "extension_service_user_test_base.h",
    "fake_crx_installer.cc",
    "fake_crx_installer.h",
    "load_error_waiter.cc",
    "load_error_waiter.h",
    "mock_crx_installer.cc",
    "mock_crx_installer.h",
    "test_extension_service.cc",
    "test_extension_service.h",
    "test_extension_system.cc",
    "test_extension_system.h",
  ]

  deps = [
    ":browser",
    "//base",
    "//components/crx_file",
    "//components/extensions/common",
    "//components/policy/core/common:test_support",
    "//components/safe_browsing/core/browser/db:database_manager",
    "//components/safe_browsing/core/browser/db:v4_test_util",
    "//components/services/unzip:in_process",
    "//components/services/unzip/content",
    "//components/sessions",
    "//components/value_store:test_support",
    "//content/public/browser",
    "//content/test:test_support",
    "//extensions:test_support",
    "//extensions/browser",
    "//extensions/browser:test_support",
    "//extensions/shell:app_shell_lib",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "api/chrome_extensions_api_client_unittest.cc",
    "api/device_permissions_manager_unittest.cc",
    "api/runtime/chrome_runtime_api_delegate_unittest.cc",
    "chrome_content_verifier_unittest.cc",
    "component_loader_unittest.cc",
  ]

  data = [
    "//base/test/data/",
    "//components/test/data/",
    "//extensions/test/data/",
  ]

  deps = [
    ":test_support",
    "//services/device/public/cpp:test_support",
  ]

  public_deps = [ "//base/test:test_support" ]
}
